name: "validate-deploy"
description: "Validate Deploy"
inputs:
  skip-verification:
    required: true
    default: false
    type: boolean
    description: "Should skip verification"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo "validate - should skip? ${{inputs.pr-number}}"
