name: "validate-deploy"
description: "Validate Deploy"
inputs:
  skip-verification:
    required: true
    default: false
    type: boolean
    description: "Should skip verification"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        day_of_week=$(date +%A)
        if [[ "$day_of_week" == "Sunday" ]]; then
          max_epoch=$(TZ=UTC date --date='TZ="Israel" 16:00' +%s)
        else
          max_epoch=$(TZ=UTC date --date='TZ="Israel" 13:00' +%s)
        fi
        
        now_epoch=$(date -d "now" +%s)
        echo "Validating time of deploy ($day_of_week) [now: $now_epoch] [max: $max_epoch]"
        if (( $now_epoch > $max_epoch )); then
          exit 1
        else
          exit 0
        fi
