name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  bump-ci:
    uses: ./.github/workflows/bump.yaml
    
  generate-ci:
    needs: bump-ci
    uses: ./.github/workflows/generate.yaml

  tests-ci:
    needs: generate-ci
    uses: ./.github/workflows/tests.yaml
