name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  bump-ci:
    uses: ./.github/workflows/bump.yaml
    
  generate-ci:
    needs: bump-ci
    uses: ./.github/workflows/generate.yaml

  tests-ci:
    needs: tests-ci
    uses: ./.github/workflows/tests.yaml
