name: "deploy"

on:
  workflow_dispatch:
    inputs:
      skip-time-gate:
        description: 'Force deploy - skip time gate'
        required: false
        type: boolean
        default: false
        
jobs:
  validate:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Validate
        uses: ./.github/actions/validate-deploy
        with:
          skip_verification: ${{inputs.skip-time-gate}}
          max_allowed_hour: "13:00"

  deploy1:
    runs-on: ubuntu-22.04
    name: deploy1
    needs: validate
    steps:
      - name: run-deploy1
        run: echo "Deploy1"
  
  deploy2:
    runs-on: ubuntu-22.04
    name: deploy2
    needs: validate
    steps:
      - name: run-deploy2
        run: echo "Deploy2"

  final:
    runs-on: ubuntu-22.04
    name: final
    needs: [deploy1, deploy2]
    steps:
      - name: final
        run: echo "Final"
