name: "deploy"

on:
  workflow_dispatch:
    inputs:
      force-deploy:
        description: 'Force'
        required: false
        type: boolean
        default: false
      max-allowed-hour:
        required: false
        default: "13"
        type: number
        description: "Define the latest permissible deployment hour (00-24) daily, with an additional 3 hours granted on Sundays."

jobs:
  validate:
    name: validate
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      
      - name: Validate
        uses: ./.github/actions/validate-deploy
        with:
          skip-verification: ${{inputs.force-deploy}}
          max-allowed-hour: ${{inputs.max-allowed-hour}}

  deploy1:
    runs-on: ubuntu-22.04
    name: deploy1
    needs: validate
    steps:
      - name: run-deploy1
        run: echo "Deploy1"
  
  deploy2:
    runs-on: ubuntu-22.04
    name: deploy2
    needs: validate
    steps:
      - name: run-deploy2
        run: echo "Deploy2"

  final:
    runs-on: ubuntu-22.04
    name: final
    needs: [deploy1, deploy2]
    steps:
      - name: final
        run: echo "Final"
