name: "Docker tests"

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build -t debi-test -f Dockerfile .

      - name: Run the docker
        run: docker run --rm debi-test
