name: "Main workflow"

on:
  push:
    paths:
      - 'src/**'
      - '.github/**'
    branches:
      - 'feat/some-branch'
  workflow_dispatch:

jobs:
  
  main:
    name: main
    uses: ./.github/workflows/sub1.yml
    with:
      param1: david
