name: "Main workflow"

on:
  push:
    # paths:
    #   - 'src/*'
    branches:
      - 'feat/some-branch'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: echo "main workflow starts"

