name: "Main workflow"

on:
  push:
    paths:
      - 'src/**'
      - '.github/**'
    branches:
      - 'feat/some-branch'
  workflow_dispatch:

jobs:
  
  get_components:
    name: get components
    uses: ./.github/workflows/get-components.yml
  
  # main:
  #   name: main
  #   runs-on: ubuntu-latest
  #   needs: [ get_components ]
  #   steps:
  #     - run: echo ${{ fromJSON(needs.get_components.outputs) }}
      
  main:
    name: main
    uses: ./.github/workflows/sub1.yml
    needs: [ get_components ]
    strategy:
      matrix:
        component: ${{ fromJSON(needs.get_components.outputs.components) }}
    with:
      param1: ${{ matrix.component }}
