name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Enter a message'     
        required: true

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print message
        run: echo "${{ github.event.inputs.message }}"
