name: Manual workflow

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      Test:
        required: true
    
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "${{ secrets.TEST }}" | sha256sum
