name: Print Release Info

on:
  release:
    types: [created]

jobs:
  print-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history to get branch information

      - name: Print release tag and branch
        run: |
          echo "Release tag: ${{ github.event.release.tag_name }}"
          BRANCH=$(git name-rev --name-only ${{ github.event.release.target_commitish }})
          echo "Original branch: $BRANCH"
