name: Release

on:
  workflow_dispatch:
  push:

jobs:
  prepare:
    runs-on: ubuntu-latest

    permissions:
      contents: read
    
    steps:
      - name: Validate Secret Length
        run: |
          if [ -z "$DOCKER_USERNAME" ]; then
            echo "DOCKER_USERNAME is not set"
          else
            echo "DOCKER_USERNAME is set and its length is: ${#DOCKER_USERNAME}"
          fi
          
          if [ -z "$DOCKER_PASSWORD" ]; then
            echo "DOCKER_PASSWORD is not set"
          else
            echo "DOCKER_PASSWORD is set and its length is: ${#DOCKER_PASSWORD}"
          fi
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
