name: "Test outputs"

on:
  push:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - prod
          - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Define env vars
        id: define_vars
        run: |
          echo "foo=bar" >> $GITHUB_OUTPUT
          echo "something=else" >> $GITHUB_OUTPUT
          echo "david=lev" >> $GITHUB_OUTPUT
      
      - name: Use vars
        run: |
          echo ${{ steps.define_vars.outputs.foo }}
          echo ${{ steps.define_vars.outputs.something }}
          echo ${{ steps.define_vars.outputs.david }}
          echo ${{ inputs.environment }}

